import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const DARK   = [5, 5, 10];
const PANEL  = [20, 20, 32];
const GREEN  = [62, 207, 142];
const CYAN   = [100, 210, 255];
const DIM    = [100, 100, 130];
const WHITE  = [240, 240, 244];
const PINK   = [255, 95, 138];
const PURPLE = [176, 156, 255];

export function exportSplitSheetPDF(release, splits) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  // ── Background ──────────────────────────────────────────────────────────────
  doc.setFillColor(...DARK);
  doc.rect(0, 0, W, H, 'F');

  // ── Header bar ──────────────────────────────────────────────────────────────
  doc.setFillColor(...PANEL);
  doc.roundedRect(10, 10, W - 20, 28, 4, 4, 'F');

  // Logo
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...GREEN);
  doc.text('SOHMNA', 18, 22);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DIM);
  doc.text('LABEL HUB', 18, 28);

  // "SPLIT SHEET" label
  doc.setFontSize(9);
  doc.setTextColor(...DIM);
  doc.text('SPLIT SHEET', W - 18, 22, { align: 'right' });
  doc.setFontSize(8);
  doc.text(new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' }), W - 18, 28, { align: 'right' });

  // ── Release info ─────────────────────────────────────────────────────────────
  let y = 50;

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text(release.title, 14, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DIM);
  const meta = [
    release.release_type?.toUpperCase(),
    release.release_date ? new Date(release.release_date + 'T00:00:00').toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' }) : null,
    release.distributor,
    release.upc ? `UPC: ${release.upc}` : null,
  ].filter(Boolean).join('   ·   ');
  doc.text(meta, 14, y);
  y += 5;

  // Divider
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(0.5);
  doc.line(14, y, W - 14, y);
  y += 8;

  // ── Splits table ─────────────────────────────────────────────────────────────
  const total = splits.reduce((s, r) => s + Number(r.split_pct), 0);
  const balanced = Math.abs(total - 100) < 0.01;

  autoTable(doc, {
    startY: y,
    head: [['Artist', 'Role', 'Split %']],
    body: splits.map(s => [
      s.artists?.stage_name || '—',
      s.role?.toUpperCase() || '—',
      `${Number(s.split_pct).toFixed(2)}%`,
    ]),
    foot: [[
      { content: 'TOTAL', styles: { fontStyle: 'bold', textColor: WHITE } },
      '',
      { content: `${total.toFixed(2)}%`, styles: { fontStyle: 'bold', textColor: balanced ? GREEN : PINK } },
    ]],
    theme: 'plain',
    styles: {
      font: 'helvetica',
      fontSize: 11,
      textColor: WHITE,
      cellPadding: { top: 4, bottom: 4, left: 6, right: 6 },
    },
    headStyles: {
      fontSize: 8,
      fontStyle: 'normal',
      textColor: DIM,
      fillColor: PANEL,
      lineWidth: 0,
    },
    bodyStyles: {
      fillColor: false,
      lineColor: [30, 30, 50],
      lineWidth: { bottom: 0.2 },
    },
    footStyles: {
      fillColor: PANEL,
      lineWidth: 0,
      fontSize: 11,
    },
    columnStyles: {
      2: { halign: 'right' },
    },
    margin: { left: 14, right: 14 },
  });

  y = doc.lastAutoTable.finalY + 12;

  // ── Balance indicator ────────────────────────────────────────────────────────
  if (!balanced) {
    doc.setFillColor(244, 160, 176, 0.1);
    doc.setDrawColor(...PINK);
    doc.setLineWidth(0.4);
    doc.roundedRect(14, y, W - 28, 10, 2, 2, 'FD');
    doc.setFontSize(9);
    doc.setTextColor(...PINK);
    doc.text(`⚠  Splits total ${total.toFixed(2)}% — does not equal 100%`, 18, y + 6.5);
    y += 16;
  }

  // ── Signature lines (owner only) ─────────────────────────────────────────────
  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(...DIM);
  doc.text('SIGNATURES', 14, y);
  y += 6;

  const sigCols = Math.min(splits.length, 2);
  const colW = (W - 28) / sigCols;

  splits.slice(0, 4).forEach((s, i) => {
    const col = i % sigCols;
    const row = Math.floor(i / sigCols);
    const x = 14 + col * colW;
    const sy = y + row * 28;

    doc.setDrawColor(...DIM);
    doc.setLineWidth(0.3);
    doc.line(x, sy + 14, x + colW - 10, sy + 14);

    doc.setFontSize(9);
    doc.setTextColor(...WHITE);
    doc.text(s.artists?.stage_name || 'Artist', x, sy + 19);

    doc.setFontSize(8);
    doc.setTextColor(...DIM);
    doc.text(s.role?.toUpperCase() || '', x, sy + 24);
  });

  // ── Footer ───────────────────────────────────────────────────────────────────
  doc.setFontSize(7);
  doc.setTextColor(...DIM);
  doc.text('Generated by Sohmna Label Hub  ·  sohmna.com', W / 2, H - 10, { align: 'center' });

  doc.save(`${release.title.replace(/[^a-z0-9]/gi, '_')}_split_sheet.pdf`);
}

export function exportRoyaltyStatementPDF({ artistName, entries, periodStart, periodEnd, labelName }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  // Background
  doc.setFillColor(...DARK);
  doc.rect(0, 0, W, H, 'F');

  // Header bar
  doc.setFillColor(...PANEL);
  doc.roundedRect(10, 10, W - 20, 30, 4, 4, 'F');

  // Label name
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...CYAN);
  doc.text((labelName || 'SOHMNA').toUpperCase(), 18, 22);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DIM);
  doc.text('LABEL HUB', 18, 28);

  // Doc type + date
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text('ROYALTY STATEMENT', W - 18, 22, { align: 'right' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DIM);
  doc.text(`Generated ${new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' })}`, W - 18, 29, { align: 'right' });

  let y = 52;

  // Artist name
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text(artistName, 14, y);
  y += 7;

  // Period
  const fmt = d => new Date(d + 'T00:00:00').toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DIM);
  doc.text(`Period: ${fmt(periodStart)} — ${fmt(periodEnd)}`, 14, y);
  y += 3;

  // Cyan rule
  doc.setDrawColor(...CYAN);
  doc.setLineWidth(0.6);
  doc.line(14, y, W - 14, y);
  y += 10;

  // Filter entries to period
  const inRange = entries.filter(e => {
    if (!e.date) return false;
    return e.date >= periodStart && e.date <= periodEnd;
  });

  // Build table rows
  const TYPE_SIGN = { advance: -1, expense: -1, royalty: 1, payment: 1 };
  const rows = inRange.map(e => {
    const sign = TYPE_SIGN[e.type] ?? 1;
    const abs = Math.abs(parseFloat(e.amount));
    return [
      e.date,
      e.type.toUpperCase(),
      e.description || '—',
      e.releases?.title || '—',
      { content: `${sign > 0 ? '+' : '-'}$${abs.toFixed(2)}`, styles: { textColor: sign > 0 ? CYAN : PINK, halign: 'right' } },
    ];
  });

  if (rows.length) {
    autoTable(doc, {
      startY: y,
      head: [['DATE', 'TYPE', 'DESCRIPTION', 'RELEASE', 'AMOUNT']],
      body: rows,
      theme: 'plain',
      styles: { font: 'helvetica', fontSize: 10, textColor: WHITE, cellPadding: { top: 4, bottom: 4, left: 5, right: 5 } },
      headStyles: { fontSize: 8, fontStyle: 'normal', textColor: DIM, fillColor: PANEL, lineWidth: 0 },
      bodyStyles: { fillColor: false, lineColor: [30, 30, 50], lineWidth: { bottom: 0.2 } },
      columnStyles: { 0: { cellWidth: 24 }, 1: { cellWidth: 22 }, 4: { halign: 'right', cellWidth: 28 } },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 10;
  } else {
    doc.setFontSize(10);
    doc.setTextColor(...DIM);
    doc.text('No transactions in this period.', 14, y);
    y += 14;
  }

  // Summary panel
  const credits = inRange.filter(e => TYPE_SIGN[e.type] > 0).reduce((s, e) => s + Math.abs(parseFloat(e.amount)), 0);
  const debits  = inRange.filter(e => TYPE_SIGN[e.type] < 0).reduce((s, e) => s + Math.abs(parseFloat(e.amount)), 0);
  const balance = credits - debits;

  doc.setFillColor(...PANEL);
  doc.roundedRect(14, y, W - 28, 36, 3, 3, 'F');

  doc.setFontSize(8);
  doc.setTextColor(...DIM);
  doc.text('TOTAL CREDITS', 22, y + 10);
  doc.text('TOTAL DEBITS', 22, y + 20);
  doc.text('NET BALANCE', 22, y + 30);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...CYAN);
  doc.text(`+$${credits.toFixed(2)}`, W - 22, y + 10, { align: 'right' });
  doc.setTextColor(...PINK);
  doc.text(`-$${debits.toFixed(2)}`, W - 22, y + 20, { align: 'right' });

  const balColor = balance >= 0 ? CYAN : PINK;
  doc.setTextColor(...balColor);
  doc.text(`${balance >= 0 ? '+' : '-'}$${Math.abs(balance).toFixed(2)}  (${balance >= 0 ? 'RECOUPED' : 'UNRECOUPED'})`, W - 22, y + 30, { align: 'right' });

  // Footer
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DIM);
  doc.text('Generated by Sohmna Label Hub  ·  Confidential', W / 2, H - 10, { align: 'center' });

  const safe = s => s.replace(/[^a-z0-9]/gi, '_');
  doc.save(`${safe(artistName)}_royalty_statement_${periodStart}_${periodEnd}.pdf`);
}
